name       : med-c
version    : 4.1.0
release    : 3
source     :
    - https://files.salome-platform.org/Salome/other/med-4.1.0.tar.gz : 847db5d6fbc9ce6924cb4aea86362812c9a5ef6b9684377e4dd6879627651fce
homepage   : https://www.salome-platform.org/user-section/about/med
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Meshed data exchange library
description: |
    MED-fichier (Modélisation et Echanges de Données, in English Modelisation and Data Exchange) is a library to store and exchange meshed data or computation results. It uses the HDF5 file format to store the data.
builddeps  :
    - pkgconfig(hdf5)
    - pkgconfig(python3)
    - swig
setup      : |
    %patch -p1 < $pkgfiles/hdf5-1.12.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    rm -rf $installdir/usr/bin/test*
check      : |
    %ninja_check
